export const queryKeys = {
  movies: "movies",
  popular: "popular",
  similar: "similar",
  upcoming: "upcoming",
  review: "review",
  videos: "videos",
  search: "search",
  person: "person",
  credit: "credit",
  auth: "auth",
  createSession: "createSession",
  token: "token",
  popular_Tv: "popular-tv",
  latest_Tv: "latest-Tv",
  top_Rated_Tv: "top-Rated-Tv",
  tv_ON_THE_AIR: "tv-ON-THE-AIR",
  AiringToday: "AiringToday",
};
